version: "3.8"
services:
  filerun:
    build:
      context: .
    container_name: filerun
    volumes:
      - /some/location:/var/www/html
      - ./some/other/location:/user-files
    restart: unless-stopped
    environment:
      FR_DB_HOST: db
      FR_DB_PORT: 3306
      FR_DB_NAME: ${MARIADB_DB_NAME}
      FR_DB_USER: ${MARIADB_DB_USER}
      FR_DB_PASS: ${MARIADB_DB_PASSWORD}
      APACHE_RUN_USER: www-data
      APACHE_RUN_USER_ID: 33
      APACHE_RUN_GROUP: www-data
      APACHE_RUN_GROUP_ID: 33
    networks:
      - filerun
      - caddy
    depends_on:
      - filerun-mariadb
    labels:
      caddy: ${DOMAIN}
      caddy.log.level: INFO
      caddy.log.output: file /data/logs/filerun/latest.log
      caddy.log.output.roll_size: 10MB
      caddy.log.output.roll_keep: 10
      # Use the ACME HTTP-01 challenge to get a cert for the configured domain.
      caddy.tls.dns: cloudflare ${CLOUDFLARE_API_TOKEN}
      caddy.tls.resolvers: 1.1.1.1
      caddy.reverse_proxy: "{{upstreams 80}}"
      caddy.reverse_proxy.header_up: Host ${DOMAIN}
      caddy.file_server: ""
      caddy.encode: gzip
      caddy.header.Strict-Transport-Security: '"max-age=31536000;"' # Recommended security hardening for fileservers
      caddy.header.X-XSS-Protection: '"1; mode=block;"'             # Recommended security hardening for fileservers
      caddy.header.X-Content-Type-Options: "nosniff"                # Seems required to open files in OnlyOffice
      caddy.header.X-Frame-Options: "SAMEORIGIN"
      caddy.header.X-Forwarded-Proto: https

  filerun-mariadb:
    image: mariadb:10.5
    container_name: filerun-mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MARIADB_DB_NAME}
      MYSQL_USER: ${MARIADB_DB_USER}
      MYSQL_PASSWORD: ${MARIADB_DB_PASSWORD}
    restart: unless-stopped
    networks:
      - filerun
    volumes:
      - /some/location:/var/lib/mysql

networks:
  caddy:
    external: true
  filerun:
    driver: bridge